import { z } from "zod";
import AbstractNamedDTO from "../AbstractNamedDTO";
import AbstractMagicDTO from "./AbstractMagicDTO";
import NivelDTO from "./NivelDTO";

export enum MagiaEnum {
	abrigo = "a0",
	adestramento = "a1",
	aeroataque = "a2",
	aeromanipulacao = "a3",
	alucinacao = "a4",
	amizade = "a5",
	analise = "a6",
	animacaoMetalica = "a7",
	animacaoVegetal = "a8",
	anulacaoMistica = "a9",
	apelo = "a10",
	aprimorarHabilidades = "a11",
	areaDePaz = "a12",
	armadilha = "a13",
	armadilhaNatural = "a14",
	armaduraElemental = "a15",
	armaduraNatural = "a16",
	arqueirismo = "a17",
	assimilacao = "a18",
	assombracao = "a19",
	ataqueImpetuoso = "a20",
	ataqueTermico = "a21",
	atoFalho = "a22",
	auraAmeacadora = "a23",
	auraDivina = "a24",
	auraEmocional = "a25",
	auraMagica = "a26",
	ausencia = "a27",
	auxilioIncerto = "a28",
	auxilioNatural = "a29",
	avaliacao = "a30",
	azar = "a31",
	barreiraMistica = "b0",
	bencao = "b1",
	bencaoSelvagem = "b2",
	biogerminacao = "b3",
	bloqueio = "b4",
	boato = "b5",
	bolaDeFogo = "b6",
	bote = "b7",
	bravura = "b8",
	cacadaMarcada = "c0",
	campoabencoado = "c1",
	camuflagem = "c2",
	cancaoDoAlento = "c3",
	cancaoDoAnimo = "c4",
	cancaoDoSono = "c5",
	cancaoDoTormento = "c6",
	cataclisma = "c7",
	chuvaAcida = "c8",
	circuloDeProtecao = "c9",
	clarividencia = "c10",
	cobertura = "c11",
	comandoDePaz = "c12",
	comunhaoNatural = "c13",
	conhecimento = "c14",
	conhecimentoLinguistico = "c15",
	conhecimentoNatural = "c16",
	conjuracaoNatural = "c17",
	conjurarObjetos = "c18",
	contatosMentais = "c19",
	contatosMusicais = "c20",
	controle = "c21",
	controleClimatico = "c22",
	controleMecanico = "c23",
	conversaoEnergetica = "c24",
	convivencia = "c25",
	convocacao = "c26",
	convocacaoAnimal = "c27",
	coordenacao = "c28",
	corrente = "c29",
	covardia = "c30",
	criacao = "c31",
	criptogramaMistico = "c32",
	curasEspirituais = "c33",
	curasFisicas = "c34",
	curasHeroicas = "c35",
	dadivasDaGuerra = "d0",
	dardosDeGelo = "d1",
	degeneracaoFisica = "d2",
	desertificacao = "d3",
	desintegracao = "d4",
	deslocamentoNatural = "d5",
	despistamento = "d6",
	destrezaAnimal = "d7",
	deteccaoDeMagia = "d8",
	detectarIntencao = "d9",
	distracao = "d10",
	doencas = "d11",
	dominacaoAnimal = "d12",
	dominio = "d13",
	dominioMental = "d14",
	dominioNatural = "d15",
	elementalDaAgua = "e0",
	elementalDaTerra = "e1",
	elementalDoAr = "e2",
	elementalDoFogo = "e3",
	eloAnimal = "e4",
	eloEmpatico = "e5",
	empatia = "e6",
	encantamento = "e7",
	encolhimento = "e8",
	esconjuracao = "e9",
	escrita = "e10",
	escriturasMisticas = "e11",
	escudoMistico = "e12",
	escudoProtetor = "e13",
	escudoTermico = "e14",
	escuridao = "e15",
	esplendor = "e16",
	esquecimento = "e17",
	explosaoMistica = "e18",
	fabricacaoDivina = "f0",
	faro = "f1",
	fascinio = "f2",
	feixesIncandescentes = "f3",
	fitogenese = "f4",
	fogoDivino = "f5",
	forcaMutua = "f6",
	forcaSagrada = "f7",
	forcarDisputa = "f8",
	formaDePedra = "f9",
	formaFluida = "f10",
	garras = "g0",
	geoanimacao = "g1",
	geomanipulacao = "g2",
	geoprotecao = "g3",
	habilidadeAnimal = "h0",
	herbologia = "h1",
	hidromanipulacao = "h2",
	hidrotolerancia = "h3",
	iconeSagrado = "i0",
	identificacao = "i1",
	ilusoes = "i2",
	imagem = "i3",
	intuicao = "i4",
	invisibilidade = "i5",
	iraDivina = "i6",
	lagrimaDeDragao = "l0",
	laminaDeLuz = "l1",
	leitura = "l2",
	leituraDeHabitos = "l3",
	leituraLabial = "l4",
	lendaViva = "l5",
	lendas = "l6",
	levitacao = "l7",
	libertacao = "l8",
	licantropiaLupina = "l9",
	linguagem = "l10",
	malabarismo = "m0",
	maldicoes = "m1",
	manipulacaoDeLuz = "m2",
	manipularConfianca = "m3",
	marcaArcana = "m4",
	marcaDaMorte = "m5",
	medo = "m6",
	memorizacao = "m7",
	meteoros = "m8",
	mimetismoAnimal = "m9",
	modificarEspirito = "m10",
	motivacao = "m11",
	mutacao = "m12",
	mutualidade = "m13",
	necroanimacao = "n0",
	necroconhecimento = "n1",
	necropotencia = "n2",
	obstinacao = "o0",
	olharDoPredador = "o1",
	ondaDestrutiva = "o2",
	ondaPsiquica = "o3",
	ordens = "o4",
	orientacao = "o5",
	paralisia = "p0",
	peleDeArvore = "p1",
	perspicacia = "p2",
	pesadelo = "p3",
	piromanipulacao = "p4",
	piroprotecao = "p5",
	planoMistico = "p6",
	possessao = "p7",
	presencaIntimidadora = "p8",
	previsibilidade = "p9",
	primor = "p10",
	prisao = "p11",
	prisaoVegetal = "p12",
	projecao = "p13",
	projecaoSensorial = "p14",
	protecaoAnimal = "p15",
	protecaoDivina = "p16",
	protecaoMental = "p17",
	protecaoNatural = "p18",
	protecaoVegetal = "p19",
	pseudoconsciencia = "p20",
	pseudomateria = "p21",
	purificacao = "p22",
	putrefacao = "p23",
	quebraDeEncantos = "q0",
	raioEletrico = "r0",
	raizesMisticas = "r1",
	rastreamento = "r2",
	recuperacaoFisica = "r3",
	refletir = "r4",
	regeneracao = "r5",
	relampagos = "r6",
	replicas = "r7",
	resistencia = "r8",
	resistenciaElemental = "r9",
	ressurreicao = "r10",
	restauracao = "r11",
	retencaoMagica = "r12",
	retorno = "r13",
	ritualDeSangue = "r14",
	ruido = "r15",
	runas = "r16",
	sacrificio = "s0",
	sagracao = "s1",
	santuarioNatural = "s2",
	seducao = "s3",
	sentidoNatural = "s4",
	serDeAgua = "s5",
	serenidade = "s6",
	sextoSentido = "s7",
	silencio = "s8",
	sono = "s9",
	sorte = "s10",
	sosia = "s11",
	sugestao = "s12",
	telecinese = "t0",
	tensao = "t1",
	terremoto = "t2",
	toqueGelido = "t3",
	transformacao = "t4",
	transformacaoMetalica = "t5",
	transmutacao = "t6",
	transporteDimensional = "t7",
	unidadeNatural = "u0",
	velocidade = "v0",
	ventriloquismo = "v1",
	vigilia = "v2",
	vigor = "v3",
	vinculo = "v4",
	vinculoVital = "v5",
	visaoAnimal = "v6",
	visaoDeBatalhas = "v7",
	visaoDeCena = "v8",
	visaoMistica = "v9",
	visaoNoturna = "v10",
	visaoTermica = "v11",
}

/*
const getFirst = (c: string) => c[0]
const mapa = new Map<string, number>()

const next = list.map(i => i.split("=")[0].trim()).map(i => {
    const c = getFirst(i)
    const val = mapa.has(c) ? mapa.get(c)! + 1 : 0

    const output = `${i} = "${c}${val}",`
    mapa.set(c, val)

    return output
})

console.log(next.join("\n"))
*/

const MagiaDTO = AbstractNamedDTO.extend({
	extra: z.string().array().optional(),
	niveis: NivelDTO.array(),
}).merge(AbstractMagicDTO);

type Magia = z.infer<typeof MagiaDTO>;

export type { Magia };
export default MagiaDTO;
