export enum RoutePath {
	ROOT = "/",
	FICHAS = "/fichas",
	FICHA = "ficha/:id",
	DADO = "/dado",
	MAGIAS = "/magias",
	MAGIA = "/magia/:id",
	HABILIDADES = "/habilidades",
	HABILIDADE = "/habilidade/:id",
	MAPAS = "/mapas",
	MAPA = "/mapa/:id",
	CONFIGURACOES = "/configuracoes",
	SOBRE = "/sobre",
	EDITAR_FICHA = "/editar_ficha/:id",
}
